#!/usr/bin/ruby

$: << File.expand_path(File.dirname(__FILE__))

require "rubygems"

require "json"
require "thor"

require "lib/cli"
require "lib/manifest_handler"
require "lib/view"
require "lib/distro"
require "lib/rpm_manifestizer"
require "lib/settings"

def get_involved text, id = nil
  puts "You can help and get involved:"
  puts text
  if id
    puts "More info: https://github.com/cornelius/inqlude/issues/#{id}"
  end
end

distro = Distro.detect
if !distro
  STDERR.puts "Warning: unable to detect distro."
end

Cli.settings = Settings.new
Cli.distro = distro

Cli.check_unknown_options!
Cli.start ARGV
