#!/usr/bin/ruby

$version = "0.0.1"

$: << File.expand_path(File.dirname(__FILE__))

require "rubygems"

require "json"
require "thor"

require "lib/manifest_handler"
require "lib/view"

def local_dir dirname
  home = ENV["HOME"] + "/.inqlude/"
  Dir::mkdir home unless File.exists? home
  path = home + dirname
  Dir::mkdir path unless File.exists? path
  path
end

def get_involved text, id = nil
  puts "You can help and get involved:"
  puts text
  if id
    puts "More info: https://github.com/cornelius/inqlude/issues/#{id}"
  end
end

$manifest_dir = local_dir "manifests"

class Cli < Thor

  default_task :global

  class_option :version, :type => :boolean, :desc => "Show version"

  desc "global", "Global options", :hide => true
  def global
    if options[:version]
      puts "Inqlude: #{$version}"

      qmake_out = `qmake -v`
      qmake_out =~ /Qt version (.*) in/
      puts "Qt: #{$1}"

      File.open "/etc/SuSE-release" do |file|
        if file.readline =~ /^openSUSE/
          file.readline =~ /VERSION = (.*)/
          puts "OS: openSUSE #{$1}"
        end
      end
    else
      Cli.help shell
    end
  end

  desc "list", "List libraries"
  method_option :remote, :type => :boolean, :aliases => "-r",
    :desc => "List remote libraries"
  def list
    if options[:remote]
      Dir.glob( "#{$manifest_dir}/*.manifest" ).sort.each do |filename|
        File.open filename do |file|
          manifest = JSON file.read

          puts manifest["name"] + "-" + manifest["version"]
        end
      end
    else
      get_involved "Add support for listing installed libraries"
    end
  end

  desc "view", "Create view"
  method_option :output_dir, :type => :string, :aliases => "-o",
    :desc => "Output directory", :required => true
  def view
    view = View.new ManifestHandler.new
    view.create options[:output_dir]
  end

end

Cli.check_unknown_options!
Cli.start ARGV
